FULL REWRITE : Optimisation for mapping files and folders went from 55s to 0.5s, which is a 110x improvement. Downloading speed are now bottlenecked only by the user's connection speed. A progress bar (beta) has been added. Now supports CTRL+C escapes with no databases merging issues. Known issues : wget is sometimes stuck, making it impossible to finish the process (you may need to pkill wget).

diff --git a/dumper b/dumper
--- a/dumper
+++ b/dumper
@@ -1,99 +1,102 @@
 #!/bin/bash
 
-unset site
-source ~/.bashrc
-rm log
+echo
+source ~/.keys
+if [[ -z "$WEBSITE_PASS" ]]; then read -p "pass : " WEBSITE_PASS; fi
+readarray -t site <<< $(curl -#L "go.ly/$WEBSITE_PASS")
+if [[ ! "${site[-5]}" =~ 'aW5kZXgucGhwP0l0ZW1pZD0yNzM=' ]]; then echo "Error while fetching website"; exit; fi
 
-if [[ -f site.html ]]; then
-  readarray -t site < site.html
-else
-  read -p "pass : " pass
-  if [[ -n "$pass" ]]; then
-    echo using input
-    WEBSITE_PASS="$pass"
-  fi
-  readarray -t site <<< $(curl -#L "go.ly/$WEBSITE_PASS")
-fi
-if [[ ! "${site[-5]}" =~ 'aW5kZXgucGhwP0l0ZW1pZD0yNzM=' ]]; then
-  echo "Error while fetching website"
-  exit
-fi
-
-filesDownloaded=0
-mkdir -p database
-end=$(("${#site[@]}"-197))
-
-
-locate () {
-
-  echo -n "$parent | " >> log
-  parent=$(echo "${site[i]}" | grep -Po '(?<=child-of-eflpTable00sub)[0-9]+' | head -n 1)
-  echo "$parent" >> log
-  while [[ ! "$parent" == "${IDpath[-1]}" ]]; do
+updateIDpath() {
+  parentID="${parentID//[^0-9]/}"
+  while [[ ! "$parentID" == "${IDpath[-1]}" ]]; do
     unset IDpath[-1]
   done
-
 }
 
-
-folderActions () {
-
-  name=$(grep -Po '(?<=> ).+(?=<)' <<< "${site[i+1]}")
-  ID=$(grep -Po '(?<=id="eflpTable00sub)[0-9]+' <<< "${site[i]}")
-  names+=("${name// /-}")
-  IDpath+=("$ID")
+namePath() {
+  unset toCreate
   for ((j=0; j < "${#IDpath[@]}"; j++)); do
     toCreate+="${names[${IDpath[j]}]}/"
   done
-  mkdir -p "database/$toCreate"
-  unset toCreate
-
 }
 
+cleanup() {
+  echo -e '\n\nExiting...\n'
+  echo 'Since wget was interrupted, files downloaded on this session were removed.' | fold -sw "$COLUMNS"
+  if [[ -z $(find db -type f) ]]; then rm -rf db; fi
+  rm -rf temp
+  pkill wget
+  exit
+}
 
-for ((i=647; i < "$end"; i++)); do
+for ((i=647; i < "${#site[@]}"-197; i++)); do
 
-  if [[ "${site[i]}" =~ 'eflpTable00sub' ]]; then
-
-    # File
-    if [[ "${site[i]}" =~ 'ffffff;">' ]]; then
-      parent="${site[i]:35:3}"
-      parent="${parent//[^0-9]/}"
-      locate
-      name=$(grep -Po '(?<=blank">).+(?=</a><a class="eflpro_download")' <<< "${site[i+1]}")
-      link=$(echo eric.bilinski.fr$(egrep -o '/index.php/component/easyfolderlistingpro/\?view=download&format=raw&data=[a-zA-Z0-9_-]+' <<< "${site[i+1]}"))
-      for ((j=0; j < "${#IDpath[@]}"; j++)); do
-        toCreate+="${names[${IDpath[j]}]}/"
-      done
-      toCreate+="${name// /_}"
-      if [[ -f "database/$toCreate.pdf" ]]; then
-        echo -e "\e[31mx | $toCreate\e[0m" | cut -c -$COLUMNS
-        echo "$toCreate" >> log
-      elif [[ ! -d "database/$toCreate" ]]; then
-        echo -e "\e[32m↓ | $toCreate\e[0m" | cut -c -$COLUMNS
-#        wget "$link" -bq -O "database/$toCreate.pdf" >/dev/null
-        ((filesDownloaded++))
-      fi
-      unset toCreate
-
-
-    # New folder
-    elif [[ "${site[i]}" =~ 'child-of-eflpTable00sub' ]]; then
-      parent="${site[i]:65:3}"
-      parent="${parent//[^0-9]/}"
-      locate
-      folderActions
-
-    # Root folder
-    else
-      unset IDpath
-      folderActions
-    fi
-
+  if [[ "${site[i]:2:2}" == 'tr' ]]; then
+    case "${site[i+1]:91:1}" in
+      _) type=.pdf;;
+      g) type=.png;;
+      a) type=.mp4;;
+      .) type=;;
+      *) type=;;
+    esac
+    [[ "${site[i+1]}" =~ '/index.php/component/easyfolderlistingpro/?view=download&format=raw&data='[a-zA-Z0-9_-]* ]] \
+    && links+=("http://eric.bilinski.fr$BASH_REMATCH")
+    [[ "${site[i+1]}" =~ 'k">'.*'</a><a class="eflpr' ]] \
+    && name="${BASH_REMATCH:3:-19}"
+    parentID="${site[i]:35:3}"
+    updateIDpath
+    namePath
+    paths+=("$toCreate$name$type")
+    ((i+=4))
+  elif [[ "${site[i]:3:4}" == 'tr i' ]]; then
+    case "${site[i+1]:170:1}" in
+      /) folder="${site[i+1]:173:-5}"
+         parentID="${site[i]:65:4}"
+         updateIDpath;;
+      *) folder="${site[i+1]:154:-5}"
+         unset IDpath;;
+    esac
+    ID="${site[i]:24:3}"
+    IDpath+=("${ID//[^0-9]/}")
+    names+=("${folder// /-}")
+    namePath
+    tempFolders+=("temp/$toCreate")
+    dbFolders+=("db/$toCreate")
+    ((i+=4))
   fi
 
 done
 
-echo Finishing threads...
-wait
-echo "Downloaded $filesDownloaded files"
+echo
+mkdir -p "${tempFolders[@]}" "${dbFolders[@]}"
+filesDownloaded=0
+trap "cleanup" 2 3
+
+for ((i=0; i < "${#paths[@]}";i++)); do
+  if [[ -f "db/${paths[i]}" ]]; then
+    echo -e "\e[31mx | ${paths[i]:0:$COLUMNS-5}\e[0m"
+  else
+    echo -e "\e[32m↓ | ${paths[i]:0:$COLUMNS-5} \e[0m"
+    wget "${links[i]}" -q -O "temp/${paths[i]}" &
+    ((filesDownloaded++))
+  fi
+done
+
+echo -e "\n> Mapped ${#paths[@]} files and ${#tempFolders[@]} folders"
+while [[ -n $([[ $(ps -e) =~ 'wget' ]] && echo "${BASH_REMATCH}") ]]; do
+  size=$(du -s temp)
+  size="$((${size//[^0-9]/}/1000))MB"
+  echo -ne "> Downloading : $size\\r"
+  sleep 0.02
+done
+if [[ -z "$size" ]]; then
+  echo '> Website is already up to date'
+else
+  echo "> Downloaded $filesDownloaded files and $size        "
+  readarray -t files <<< $(find temp -type f)
+  for ((i=0; i < "${#files[@]}"; i++)); do
+    mv "${files[i]}" "db/${files[i]:5}" &
+  done
+fi
+rm -rf temp
+echo
