almost there

diff --git a/dumper b/dumper
--- a/dumper
+++ b/dumper
@@ -56,23 +56,24 @@ menu() {
     fi
   done
 
-  echo -e '\e[36m\n[ø] - All options\e[0m'
+  echo -e '\e[36m\n[ø|a] - All options\e[0m'
   echo -e "\e[31m[e] - Exit\n\e[0m"
-  read -p "Option : " choice
+  if [[ -z "$choice" ]]; then
+    read -p "Option : " choice
+  fi
   unset usePth useUrl
-  trap 'tput cnorm; exit' 2 3
-  tput civis
   echo
 
   case "$choice" in
     [1-4])
       usePath=("${paths[choice-1]}")
       useUrl=("${urls[choice-1]}");;
-    '')
+    ''|a)
       usePath+=("${paths[@]}")
       useUrl+=("${urls[@]}");;
     e)exit;;
-    *)menu 'error' 'Invalid input'
+    *)unset choice
+      menu 'error' 'Invalid input'
       return;;
   esac
 
@@ -80,6 +81,8 @@ menu() {
     curl -s "eric.bilinski.fr/index.php/classes/ts/${useUrl[i]}" -H 'Cookie: 6319cb2653680593249bdebaaa628a80='"$cookie"'' -o .data/"${usePath[i]}".new &
     pid["$i"]="$!"
   done
+  trap 'tput cnorm; exit' 2 3
+  tput civis
   jumpUp='\e[A'
   jumpDown=''
   spinner=('-' '\\' '|' '/')
@@ -112,7 +115,6 @@ menu() {
   tput cnorm
   trap "cleanup" 2 3
   unset paths
-  filesDownloaded=0
 
   if [[ "${usePath[@]}" =~ 'annals' ]]; then
     usedPath='annals'
@@ -123,11 +125,11 @@ menu() {
     parser1
   fi
   if [[ "${usePath[@]}" =~ 'dns' ]]; then
-    readarray -t site <<< $(cat .data/dns)
+    usedPath='dns'
     echo 'dns section not supported yet'
   fi
   if [[ "${usePath[@]}" =~ 'photos' ]]; then
-    readarray -t site <<< $(cat .data/photos)
+    usedPath='photos'
     echo 'photos section not supported yet'
   fi
 
@@ -151,7 +153,6 @@ namePath() {
 
 cleanup() {
   echo -e '\n\nExiting...\n'
-  echo 'Since wget was interrupted, files downloaded on this session were removed.' | fold -sw "$COLUMNS"
   rm -rf tempannals/ tempexercices/ tempdns/ tempphotos/
   pkill wget
   exit
@@ -203,23 +204,22 @@ parser1() {
 downloader() {
 
   mkdir -p "${tempFolders[@]}" "${finalFolders[@]}"
+  filesDownloaded=0
 
-  for ((i=0; i < "${#paths[@]}";i++)); do
-    if [[ -f "$usedPath/${paths[i]}" ]]; then
+  for ((i=0; i < "${#paths[@]}"; i++)); do
+    if [[ -f "${paths[i]}" ]]; then
       echo -e "\e[31mx | ${paths[i]:0:$COLUMNS-5}\e[0m"
     else
       echo -e "\e[32m↓ | ${paths[i]:0:$COLUMNS-5} \e[0m"
-      echo wget "${links[i]}"' -q -O '"${paths[i]}"
+      wget "${links[i]}" -q -O "temp${paths[i]}" && mv "temp${paths[i]}" "${paths[i]}" && ((filesDownloaded++)) && echo a &
     fi
   done
 
   echo -e "\n> Mapped ${#paths[@]} files and ${#finalFolders[@]} folders"
 
-  exit
-
   while [[ -n $([[ $(ps -e) =~ 'wget' ]] && echo "${BASH_REMATCH}") ]]; do
     size=$(du -sc --block-size=1M tempannals/ tempexercices/ tempdns/ tempphotos 2>/dev/null | tail -n 1)
-    echo -ne "> Downloading : $sizeMB\\r"
+    echo -ne "> Downloading : $filesDownloaded/${#paths[@]}\\r"
     sleep 0.05
   done
 
@@ -227,15 +227,11 @@ downloader() {
     echo '> Already up to date'
   else
     echo "> Downloaded $filesDownloaded files and $size        "
-    readarray -t files <<< $(find temp -type f)
-    for ((i=0; i < "${#files[@]}"; i++)); do
-      mv "${files[i]}" "$usedPath/${files[i]:5}" &
-    done
   fi
-
   rm -rf tempannals/ tempexercices/ tempdns/ tempphotos/
   echo
 
 }
 
+choice="$1"
 menu
